---
minimum_pre_commit_version: 2.4.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.

  # ----- Formatting ---------------------------------------------------------------------------->
  - repo: https://github.com/saltstack/pre-commit-remove-import-headers
    rev: 1.1.0
    hooks:
      - id: remove-import-headers

  - repo: local
    hooks:
      - id: check-cli-examples
        name: Check CLI examples on execution modules
        entry: python3 .pre-commit-hooks/check-cli-examples.py
        language: system
        files: ^src/saltext/azurerm/modules/.*\.py$

  - repo: local
    hooks:
      - id: check-docs
        name: Check rST doc files exist for modules/states
        entry: python3 .pre-commit-hooks/make-autodocs.py
        language: system
        pass_filenames: false

  - repo: https://github.com/s0undt3ch/salt-rewrite
    # Automatically rewrite code with known rules
    rev: 2.5.2
    hooks:
      - id: salt-rewrite
        alias: rewrite-docstrings
        name: Salt extensions docstrings auto-fixes
        files: ^src/saltext/azurerm/.*\.py$
        args: [--silent]

  - repo: https://github.com/s0undt3ch/salt-rewrite
    # Automatically rewrite code with known rules
    rev: 2.5.2
    hooks:
      - id: salt-rewrite
        alias: rewrite-tests
        name: Rewrite the test suite
        files: ^tests/.*\.py$
        args: [--silent, -E, fix_docstrings]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.2
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.8+
        args: [
          --py38-plus
        ]
        exclude: src/saltext/azurerm/version.py

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports
        args: [
          --py38-plus,
        ]
        exclude: src/saltext/azurerm/version.py

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [-l 100]
        exclude: src/saltext/azurerm/version.py

  - repo: https://github.com/adamchainz/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        files: ^(docs/.*\.rst|src/saltext/azurerm/.*\.py)$
        additional_dependencies:
          - black==22.6.0
  # <---- Formatting -----------------------------------------------------------------------------

  # ----- Security ------------------------------------------------------------------------------>
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        alias: bandit-salt
        name: Run bandit against the code base
        args: [--silent, -lll, --skip, B701]
        exclude: src/saltext/azurerm/version.py
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        alias: bandit-tests
        name: Run bandit against the test suite
        args: [--silent, -lll, --skip, B701]
        files: ^tests/.*
  # <---- Security -------------------------------------------------------------------------------

  # ----- Code Analysis ------------------------------------------------------------------------->
  - repo: https://github.com/saltstack/mirrors-nox
    rev: v2021.6.12
    hooks:
      - id: nox
        alias: lint-src
        name: Lint Source Code
        files: ^((setup|noxfile)|src/.*)\.py$
        require_serial: true
        args:
          - -e
          - lint-code-pre-commit
          - --

  - repo: https://github.com/saltstack/mirrors-nox
    rev: v2021.6.12
    hooks:
      - id: nox
        alias: lint-tests
        name: Lint Tests
        files: ^tests/.*\.py$
        require_serial: true
        args:
          - -e
          - lint-tests-pre-commit
          - --
  # <---- Code Analysis --------------------------------------------------------------------------
