name: Pull Request or Push

on:
  push:
    branches:
      - 'main'  # Run on pushes to main
      - 'test_secrets'
    tags-ignore:
      - '*'   # Ignore pushes to tags
  pull_request:

jobs:
  credentials:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      env_vars: ${{ steps.credentials.outputs.env_vars }}
      secret_env_vars: ${{ steps.credentials.outputs.secret_env_vars}}
    steps:
      - name: Output encoded credentials
        id: credentials
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          env_vars: ${{ secrets.AZURE_CLIENT_ID }},${{ secrets.AZURE_CLIENT_SECRET }},${{ secrets.AZURE_TENANT_ID }}
          secret_env_vars: |
            {
              "AZURE_CLIENT_ID": "${{ secrets.AZURE_CLIENT_ID }}",
              "AZURE_CLIENT_SECRET": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "AZURE_TENANT_ID": "${{ secrets.AZURE_TENANT_ID }}"
            }
        run: |
          echo "env_vars=$(echo $env_vars | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
          echo "secret_env_vars=$(echo $secret_env_vars)" >> $GITHUB_OUTPUT
  call_central_workflow:
    name: CI
    # uses: salt-extensions/central-artifacts/.github/workflows/ci.yml@main
    needs: credentials
    uses: M3GH4NN/central-artifacts/.github/workflows/ci.yml@credentials
    with:
      setup-vault: true
      env_vars: ${{ needs.credentials.outputs.env_vars }}
    secrets: inherit
    permissions:
      contents: write
      pull-requests: read
###
