name: Pull Request or Push

on:
  push:
    branches:
      - 'main'  # Run on pushes to main
      - 'test_secrets'
    tags-ignore:
      - '*'   # Ignore pushes to tags
  pull_request:

jobs:
  encode_secrets:
    name: Encode Secrets
    runs-on: ubuntu-latest
    outputs:
      ENV_VARS: ${{ steps.encode.outputs.ENV_VARS }}
    steps:
      - name: Encode AZURE_* secrets
        id: encode
        run: echo ENV_VARS="$(echo -e "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}\nAZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}\nAZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" | base64 -w0)" >> $GITHUB_OUTPUT
  credentials:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      env_vars: ${{ steps.credentials.outputs.env_vars }}
    steps:
      - name: Output encoded credentials
        id: credentials
        env:
          env_vars: |
              AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
              AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
              AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          echo "AZURE_CLIENT_ID=$(echo $AZURE_CLIENT_ID | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
          echo "AZURE_CLIENT_SECRET=$(echo $AZURE_CLIENT_SECRET | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
          echo "AZURE_TENANT_ID=$(echo $AZURE_TENANT_ID | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT

  call_central_workflow:
    name: CI
    # uses: salt-extensions/central-artifacts/.github/workflows/ci.yml@main
    needs: encode_secrets
    uses: M3GH4NN/central-artifacts/.github/workflows/ci.yml@credentials
    with:
      setup-vault: true
      ENV_VARS: ${{ needs.encode_secrets.outputs.ENV_VARS }}
    permissions:
      contents: write
      pull-requests: read
###
