name: Pull Request or Push

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  call_central_workflow:
    name: CI
    runs-on: ubuntu-latest  # Specify the runner here if not already set
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Set up Azure credentials
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: echo "Azure credentials set up"

      - name: Run CI Workflow
        uses: salt-extensions/central-artifacts/.github/workflows/ci.yml@main
        with:
          setup-vault: true
