name: CI

on:
  push:
    branches:
      - azure-creds

jobs:
  get-changed-files:
    name: Get Changed Files
    uses: salt-extensions/central-artifacts/.github/workflows/get-changed-files.yml@main

  changed-files-debug:
    name: Changed Files Debug Output
    runs-on: ubuntu-latest
    if: always()
    needs:
      - get-changed-files
    steps:
      - name: Echo Changed Files Output
        run: echo "${{ toJSON(needs.get-changed-files.outputs.changed-files) }}"

  azure-login:
    name: Azure Login
    runs-on: ubuntu-latest
    steps:
      - name: Set up Azure credentials
        run: |
          echo "Logging into Azure..."
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  azure-login2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

  # Rest of your workflow steps...
