name: Pull Request or Push

on:
  push:
    branches:
      - 'main'  # Run on pushes to main
      - 'test_secrets'
    tags-ignore:
      - '*'   # Ignore pushes to tags
  pull_request:

jobs:
  call_central_workflow:
    name: CI
    uses: M3GH4NN/central-artifacts/.github/workflows/ci.yml@credentials
    # uses: salt-extensions/central-artifacts/.github/workflows/ci.yml@main
    with:
      setup-vault: true
    permissions:
      contents: write
      pull-requests: read
####
